image: Visual Studio 2017

platform: x64

install:
  - ps: Import-Module '.\scripts\appveyor-tool.ps1'
  # - ps: Bootstrap
  - cmd: git submodule update --init --recursive
  # - cmd: .\scripts\msys2.cmd

environment:
  global:
    # VERSION: 0.2.20

    # CC: gcc
    # FC: gfortran
    # BINARY: 64
    # USE_THREAD: 1
    NUM_THREADS: 64
    # NO_SHARED: 1
    # NO_CBLAS: 1
    # NO_LAPACK: 1
    # BUILD_LAPACK_DEPRECATED: 1
    # MAKE_NB_JOBS: 4
    # GEMM_MULTITHREAD_THRESHOLD: 4
    # COMMON_PROF: -pg
    #


  matrix:
    - TARGET: HASWELL
    - TARGET: SANDYBRIDGE
    - TARGET: NEHALEM

build_script:
  - cd OpenBLAS
  - mkdir build
  - cd build
  - SET PATH=C:\Miniconda36-x64;C:\Miniconda36-x64\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n opb python=3.6
  - activate opb
  - conda config --add channels conda-forge
  - conda install -y cmake flang clangdev perl libflang
  - conda install -y -c isuruf kitware-ninja
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set "LIB=%CONDA_INSTALL_LOCN%\Library\lib;%LIB%"
  - set "CPATH=%CONDA_INSTALL_LOCN%\Library\include;%CPATH%
  - cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  # - cp ../make/Makefile.rule .
  # - SET PATH=C:\msys64\usr\bin
  # - bash ..\scripts\build.sh

test_script:
  - echo Running Test
  - cd utest
  - openblas_utest

artifacts:
  - path: OpenBLAS/build/lib/*


deploy:
  description: 'OpenBLAS compiled for R'
  provider: GitHub
  auth_token:
    secure: 6VduGFAfk0LDLzJDnzCakW7vldMxkkaw4OHCYkFqyecDV9sKE+MdEP5Go4zpmt3c
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
