image: Visual Studio 2017

platform: x64

install:
  - ps: Import-Module '.\scripts\appveyor-tool.ps1'
  - ps: Bootstrap
  - cmd: git submodule update --init --recursive
  - cmd: .\scripts\msys2.cmd

# environment:

build_script:
  - cd OpenBLAS
  - cp ../make/Makefile.rule .
  - SET PATH=C:\msys64\usr\bin
  - bash -l ..\scripts\build.sh

test_script:
  - echo Running Test
  - cd utest
  - openblas_utest

artifacts:
  - path: OpenBLAS/libopenblas*.a
