image: Visual Studio 2017

platform: x64

install:
  - ps: Import-Module '.\scripts\appveyor-tool.ps1'
  - ps: Bootstrap
  - cmd: git submodule update --init --recursive
  - cmd: .\scripts\msys2.cmd

environment:
  global:
    # VERSION: 0.2.20
    # OSNAME: WINNT
    FC: gfortran
    BINARY: 64
    USE_THREAD: 1
    NUM_THREADS: 64
    NO_SHARED: 1
    NO_CBLAS: 1
    NO_LAPACK: 1
    NO_PARALLEL_MAKE: 1

    # MAKE_NB_JOBS: 4
    GEMM_MULTITHREAD_THRESHOLD: 4
    COMMON_PROF: -pg

  matrix:
    - TARGET: HASWELL
    - TARGET: SANDYBRIDGE
    - TARGET: NEHALEM

build_script:
  - cd OpenBLAS
  # - cp ../make/Makefile.rule .
  - SET PATH=C:\msys64\usr\bin
  - bash ..\scripts\build.sh

test_script:
  - echo Running Test
  - cd utest
  - openblas_utest

artifacts:
  - path: OpenBLAS/libopenblas*.a

deploy:
  release: OpenBLASR-$(target)-v$(appveyor_build_version)
  description: 'This is R compiled with the Rtools gcc, for R compatibility'
  provider: GitHub
  auth_token:
    secure: 6VduGFAfk0LDLzJDnzCakW7vldMxkkaw4OHCYkFqyecDV9sKE+MdEP5Go4zpmt3c
  artifact: OpenBLAS/libopenblas*.a
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
